### ISSUE TITLE
HoYo.Gacha v1.0.0 版本规划 Roadmap

### ISSUE THREAD

**Issue by lgou2w** [lgou2w/HoYo.Gacha#28]
### 此问题用于追踪 [`v1`](https://github.com/lgou2w/HoYo.Gacha/tree/v1) 版本分支的功能开发和未来规划

- [x] UI 界面全部重新设计。
- [x] 支持多种语言。
- [x] 支持国际版服务器账号。
- [ ] 实现抽卡记录的云存储功能。
- [ ] 实现网页版的抽卡记录获取和更新功能。
- [x] #38 
- [x] #41 
- [x] #52
- [x] #58 
- [ ] #64 
- [ ] ...

### This issue is used to track feature development and future planning for the [`v1`](https://github.com/lgou2w/HoYo.Gacha/tree/v1) branch.

- [x] The UI is completely redesigned.
- [x] Support multiple languages.
- [x] Support international server account.
- [ ] Implement cloud storage of gacha records.
- [ ] Web-based gacha record view and update features.
- [ ] ...

---

### Edited: 2024/07/27

Track: #47

### Edited: 2024/08/06

新的 UI 概念风格图：
New UI concept style:

<details>
<summary>Screenshots:</summary>

Light:
![HoYo.Gacha V1 Preview Light](https://github.com/user-attachments/assets/fbd52180-d0a6-4f0e-ace5-122ff6af6ea0)

Dark:
![HoYo.Gacha V1 Preview Dark](https://github.com/user-attachments/assets/a638c1a8-5b85-4392-8bed-a584e961d45b)

Settings:
![HoYo Gacha v1 Preview Settings](https://github.com/user-attachments/assets/9c559cf6-4325-4812-9bf1-5522b950e755)

</details>

### Edited: 2024/09/29

为了加快适配新版本，我们将使用改进后的 v0 用户界面。
未来将重新设计该界面，以添加新内容并支持在以下两个界面之间切换。
In order to speed up the adaptation to the new version, we will use the improved v0 user interface. It will be redesigned in the future to add new content and support switching between.

<details>
<summary>Screenshots:</summary>

Light:
![HoYo Gacha v1 Gacha Legacy Preview Light](https://github.com/user-attachments/assets/c4bebf64-b527-40c5-b484-093a3b82e0d3)

Dark:
![HoYo Gacha v1 Gacha Legacy Preview Dark](https://github.com/user-attachments/assets/c7c0b1a1-5b9c-4191-82e2-1db12f70ab9a)

</details>

### Edited: 2025/02/17

概览界面
Overview interface

<details>
<summary>Screenshots:</summary>

Light:

![HoYo Gacha v1 Gacha Legacy Overview Light](https://github.com/user-attachments/assets/ce07a206-0aa0-4d79-97a9-dd3295a5f2b3)

Dark:
![HoYo Gacha v1 Gacha Legacy Overview Dark](https://github.com/user-attachments/assets/696573e9-ccb0-4a34-a5d9-6bc6410c4eb7)

</details>

### Edited: 2025/05/19

分析界面
Analysis interface

<details>
<summary>Screenshots:</summary>

Light:

![HoYo Gacha v1 Gacha Legacy Analysis Light](https://github.com/user-attachments/assets/d1b30eec-4720-4926-b662-b4ea30b07596)

Dark:

![HoYo Gacha v1 Gacha Legacy Analysis Dark](https://github.com/user-attachments/assets/b651d9a5-d71a-4af1-88a7-a4365eb38fb0)

</details>

**Comment by xxbhpan** [comment]
1、希望增加up角色花费抽数统计。
2、希望在统计界面也能看到4星或者A级物品的分析。
3、希望账号管理界面的头像能够实现自定义，这样就可以挂着我们喜爱的角色了。
4、UIGF现在有3.0版本了，希望能及时跟进一下。
5、希望可以将通过链接获取的祈愿记录导出成excel形式的raw-data数据。

**Comment by Estrella-071** [comment]
1. 希望增加小保不歪機率（50/50 or 75/25 Win Rate）。
2. 希望分析中能看到 5★／4★／3★ 的紀錄，並且能切換是否顯示 5★／4★／3★。
3. 希望能看到平均 4★ 保底抽數。
4. 希望能增加分卡池查看分析／紀錄的功能。
5. 希望數字敘述增加圖示，例如：｜平均每金70抽｜ -> ｜平均保底 70 {圖示.png}｜
![MasterTape](https://github.com/user-attachments/assets/51a6a4f1-4ad1-48fe-bd93-37cd8b363986) ![EncryptedMasterTape](https://github.com/user-attachments/assets/1528c2dd-a53b-46fe-b313-5f392936419f) ![Polychrome](https://github.com/user-attachments/assets/27b372c8-cc58-4f8e-9cb1-9d526589442b) ![Pass](https://github.com/user-attachments/assets/2b33d857-9f72-41d2-afdc-eff96f224fe1) ![Special_Pass](https://github.com/user-attachments/assets/c125416e-8763-4404-adf4-2d78c9e0acb9) ![Stellar_Jades](https://github.com/user-attachments/assets/94252ad8-0bb9-4b19-93e9-b0c107c7a55d) ![AcquaintFate](https://github.com/user-attachments/assets/891cf79a-ee07-4dab-abf7-94cca84d116a) ![IntertwinedFate](https://github.com/user-attachments/assets/8c36ebd9-28ae-478a-9fe2-cfec983f72ab) ![Primogem](https://github.com/user-attachments/assets/1e982194-d46a-4428-8f58-11956a0f304d)

**Comment by boboshu** [comment]
求支持 国际服！

**Comment by lgou2w** [comment]
> 求支持 国际服！

目前 `v0` 版本是支持国际服的。只不过前端 UI 界面只有简体中文语言。

**Comment by miozx** [comment]
1. 希望可以使用WinUI等成熟设计框架
2. 希望可以自定义头像
3. 希望可以自定义显示游戏栏位，可以隐藏某个游戏（毕竟不是所有米游都玩）
4. 希望可以使用更普通的字体，而不是风格化的字体
5. 希望及时跟进UIGF新版本

**Comment by wxy97321** [comment]
1.希望增加深色模式
2.希望默认隐藏一些数据显示，以实现更简洁的面板
 以绝区零为例：
   1) 总出金率相对来说是缺乏统计意义的，因为武器池和角色池出金率不同。
   2) 折合现金缺乏意义，因为不是所有抽卡资源都是用现金换取的。
   3) 调频标签，调频覆盖时间等，可以考虑放在一个二级页面中，减少一级页面的信息量。
3.五星历史中，用x+y表示限定和非限定，有些不够直观，希望能增加文字说明
4.五星历史中，当获取的五星达到数百个时，历史页面会显得非常混乱，希望考虑增加折叠或者只显示文字的模式。

**Comment by lgou2w** [comment]
### Progress Report September 2024

为了加快适配新版本，我们将使用改进后的 v0 用户界面。
未来将重新设计该界面，以添加新内容并支持在以下两个界面之间切换。

In order to speed up the adaptation to the new version, we will use the improved v0 user interface. It will be redesigned in the future to add new content and support switching between.

<details>
<summary>Screenshots:</summary>

Light:
![HoYo Gacha v1 Gacha Legacy Preview Light](https://github.com/user-attachments/assets/c4bebf64-b527-40c5-b484-093a3b82e0d3)

Dark:
![HoYo Gacha v1 Gacha Legacy Preview Dark](https://github.com/user-attachments/assets/c7c0b1a1-5b9c-4191-82e2-1db12f70ab9a)

</details>

**Comment by UU0510** [comment]
能否增加手动补全抽卡记录的功能?之前用的小程序不能导出数据

**Comment by lgou2w** [comment]
> 能否增加手动补全抽卡记录的功能?之前用的小程序不能导出数据

有这方面的需求，届时可以在工具内或者网页内手动编辑抽卡记录。

**Comment by lgou2w** [comment]
### Progress Report February 2025

概览界面
Overview interface

<details>
<summary>Screenshots:</summary>

Light:

![HoYo Gacha v1 Gacha Legacy Overview Light](https://github.com/user-attachments/assets/ce07a206-0aa0-4d79-97a9-dd3295a5f2b3)

Dark:
![HoYo Gacha v1 Gacha Legacy Overview Dark](https://github.com/user-attachments/assets/696573e9-ccb0-4a34-a5d9-6bc6410c4eb7)

</details>

**Comment by yecongjia** [comment]
用了很多类似的工具，还是兄弟这个最好使，坐等新版。

**Comment by momaoyu** [comment]
大佬能把鸣潮也加上吗！

**Comment by lgou2w** [comment]
> 大佬能把鸣潮也加上吗！

不考虑。

**Comment by momaoyu** [comment]
> > 大佬能把鸣潮也加上吗！
> 
> 不考虑。

哭唧唧

**Comment by yecongjia** [comment]
> ### Progress Report February 2025
> 概览界面 Overview interface
> 
> Screenshots:

兄弟如果有可能的话，希望在统计方面加入一个小保底不歪概率的统计。

**Comment by lgou2w** [comment]
### Progress Report May 2025

分析界面
Analysis interface

<details>
<summary>Screenshots:</summary>

Light:

![HoYo Gacha v1 Gacha Legacy Analysis Light](https://github.com/user-attachments/assets/d1b30eec-4720-4926-b662-b4ea30b07596)

Dark:

![HoYo Gacha v1 Gacha Legacy Analysis Dark](https://github.com/user-attachments/assets/b651d9a5-d71a-4af1-88a7-a4365eb38fb0)

</details>

**Comment by Kamisato100** [comment]
最近刚更新到1.0版本，挺好的，不过想反馈两个问题：
1、字体没之前的汉仪文黑好看，是否可能添加切换现版本/以往版本字体的选项？或者如果那个旧字体可能涉及使用问题的话，让用户能自行选择系统内本地已有字体？
2、实际上最常用的是第二个标签页“分析”，因为抽完卡之后想看近期抽卡结果和统计，而第一个标签页“概览”是相对不常用的（因为抽数多的情况下少数新出金并不会对现有数据造成明显的变化，通常没有频繁去看的必要性）。是否可能考虑将“分析”标签页移到第一个，“概览”向后移？或者添加一个功能，可以在用户退出/切换游戏之后记忆之前停留在的标签页页面，这样就不需要每次进来或者切游戏之后都要额外点一下切换到“分析”页面了。
3、虽然之前那种分析页面“角色头像+数值+方格矩阵排列”的方式在金数多的情况下会显得乱，但是很适合用来展示近期一段时间（10来个金）内的出货情况，现在这种竖条滚动列表的方式虽然效率是更高更直观了，但是一次滚动只能展示4-5个金的情况，是否可能保留当前模式的情况加一个标签页还原回之前旧版的抽卡结果页面“角色头像+数值+方格矩阵排列”的展示方式？（不强求仅建议）
4、统计那个标签页现在就只有一个Coming soon...，点进去是空的，如果近期内无法完成的话先隐藏掉这个标签页入口，等做好了之后再放出来在标签页栏里可能比较好？

**Comment by niyoh120** [comment]
原神需要支持统计混池
